# Generated by Django 5.1 on 2024-08-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_description',
            field=models.TextField(blank=True),
        ),
    ]
